---
# tasks file for install-omd

# Update cache with time limit:
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 600
  tags:
    - install-omd
    - packages

# Download .deb:
- name: Fetch installation package
  get_url: 
    owner: root 
    group: root 
    mode: 0755
    url: "{{ install_omd_source_url }}"
    dest: "{{ install_omd_deb }}"
  tags:
    - install-omd
    - files

# Install .deb:
- name: Install Check_MK RAW
  apt: 
    deb: "{{ install_omd_deb }}"
    state: present
  tags:
    - install-omd
    - packages

# Run omd setup:
- name: Setup OMD
  command: omd setup
  tags:
    - install-omd
    - packages

# Run omd create:
- name: Create OMD site
  command: omd create {{ install_omd_site }}
  args:
    creates: /opt/omd/sites/{{ install_omd_site }}
  tags:
    - install-omd
    - files

# Run omd start:
- name: Start OMD site
  command: omd start {{ install_omd_site }}
  args:
    creates: /opt/omd/sites/{{ install_omd_site }}/tmp/apache/run/apache.pid
  tags:
    - install-omd
    - files

