---
# tasks file for tinkeraccess

# Use git module to clone repository:
- name: Clone repository
  git:
    bare: no
    clone: yes
    dest: "{{ tinkeraccess_repo_dest }}"
    repo: "{{ tinkeraccess_repo_source }}"
  tags:
    - tinkeraccess
    - files

# Run the install script:
- name: Run the install script
  shell: "{{ tinkeraccess_repo_dest }}/install.sh"
  args:
    chdir: "{{ tinkeraccess_repo_dest }}"
    creates: /etc/init.d/tinkerserver
  tags:
    - tinkeraccess
    - files

# Enable client:
- name: Enable tinkerAccess client
  service:
    enabled: yes
    name: "{{ tinkeraccess_client }}"
    state: started
  when: tinkeraccess_client_enabled
  tags:
    - tinkeraccess
    - services

# Disable client:
- name: Disable tinkerAccess client
  service:
    enabled: no
    name: "{{ tinkeraccess_client }}"
    state: stopped
  when: not tinkeraccess_client_enabled
  tags:
    - tinkeraccess
    - services

# Enable server:
- name: Enable tinkerAccess server
  service:
    enabled: yes
    name: "{{ tinkeraccess_server }}"
    state: started
  when: tinkeraccess_server_enabled
  tags:
    - tinkeraccess
    - services

# Disable server:
- name: Disable tinkerAccess server
  service:
    enabled: yes
    name: "{{ tinkeraccess_server }}"
    state: started
  when: not tinkeraccess_server_enabled
  tags:
    - tinkeraccess
    - services

