---
# tasks file for install-cmkagent

# Install defined packages:
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items: apt_packages
  tags:
    - apt-packages
    - packages

