---
# Graylog server
- name: hq-graylog
  hosts: hq-graylog
  become: yes
  tasks:
    - name: Install NFS client package
      apt: 
        name: nfs-common
        state: latest
      tags:
        - graylog
        - packages
    - name: Mount NFS share
      mount:
        fstype: nfs
        opts: timeo=14,_netdev
        name: "/nfs/nas2/nfs_marvin"
        src: "nas2:/nfs_marvin"
        state: mounted
      tags:
        - graylog
        - files

