---
# Roles common to all hosts:
- hosts: all
  name: All hosts
  become: yes
  roles:
    - updates
    - mkadmins
    - mksudo
    - install-cmkagent
    - apt-packages

# Production-only roles:
- hosts: production
  name: Production hosts
  become: yes
  roles:
    - fwd-syslog
    - pmbauer.tarsnap

# Active groups:
- include: hq-omd.yml
- include: hq-shell.yml
- include: hq-tinkeraccess-server.yml
- include: hq-tinkeraccess-client.yml
- include: hq-octopi.yml
- include: hq-graylog.yml

