---
# Roles common to all hosts:
- hosts: all
  name: All hosts
  become: yes
  roles:
    - updates
    - mkadmins
    - mksudo
    - install-cmkagent

# Production-only roles:
- hosts: production
  name: Production hosts
  become: yes
  roles:
    - fwd-syslog
    - pmbauer.tarsnap

# Active groups:
- include: hq-syslog.yml
- include: hq-omd.yml
- include: hq-shell.yml
- include: hq-tinkeraccess-server.yml

