---
# Roles common to all hosts:
- hosts: all
  name: All hosts
  become: yes
  roles:
    - updates
    - mkadmins
    - mksudo
    - fwd-syslog
    - install-cmkagent

# Active groups:
- include: hq-syslog.yml
- include: hq-omd.yml
