---
# tasks file for ansible-install-check_mk-client (RedHat only)

- name: Install pre-requisites
  yum:
    name: "{{ ansible_install_check_mk_client_prereqs }}"
    state: present
    update_cache: yes
  tags:
    - ansible-install-check_mk-client
    - packaging

- name: Create monitoring group
  group: 
    name: "{{ ansible_install_check_mk_client_user }}" 
    state: present
  tags:
    - ansible-install-check-mk-client
    - users

- name: Create monitoring user
  user: 
    name: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    home: "{{ ansible_install_check_mk_client_home }}"
    comment: "Check_MK Agent"
  tags:
    - ansible-install-check-mk-client
    - users

- name: Copy Linux check_mk_agent and set executable
  template: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0755
    src: check_mk_agent.linux.j2
    dest: "{{ ansible_install_check_mk_client_home }}/check_mk_agent"
  when: ansible_system.find( 'Linux' ) == 0
  tags:
    - ansible-install-check-mk-client
    - files

- name: Grant sudo for check_mk_agent to monitoring user
  template: 
    owner: root 
    group: root 
    mode: 0440
    src: 99_cmkagent.j2
    dest: /etc/sudoers.d/99_cmkagent
    validate: 'visudo -cf %s'
  tags:
    - ansible-install-check-mk-client
    - files
    - users

- name: Create directory - .ssh
  file: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0700
    path: "{{ ansible_install_check_mk_client_home }}/.ssh"
    state: directory
  tags:
    - ansible-install-check-mk-client
    - files
    - users

- name: Copy public key to .ssh/authorized_keys
  template: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0600
    src: authorized_keys.j2
    dest: "{{ ansible_install_check_mk_client_home }}/.ssh/authorized_keys"
  tags:
    - ansible-install-check-mk-client
    - files
    - users

- name: Create directory - local
  file: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0700
    path: "{{ ansible_install_check_mk_client_home }}/local"
    state: directory
  tags:
    - ansible-install-check-mk-client
    - files

- name: Generate local checks
  template: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0700
    src: "{{ item }}.j2"
    dest: "{{ ansible_install_check_mk_client_home }}/local/{{ item }}"
  with_items: "{{ ansible_install_check_mk_client_local_checks }}"
  tags:
    - ansible-install-check-mk-client
    - files

- name: Create directory - plugins
  file: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0700
    path: "{{ ansible_install_check_mk_client_home }}/plugins"
    state: directory
  tags:
    - ansible-install-check-mk-client
    - files

- name: Generate plugins
  template: 
    owner: "{{ ansible_install_check_mk_client_user }}"
    group: "{{ ansible_install_check_mk_client_user }}"
    mode: 0700
    src: "{{ item }}.j2"
    dest: "{{ ansible_install_check_mk_client_home }}/plugins/{{ item }}"
  with_items: "{{ ansible_install_check_mk_client_plugins }}"
  tags:
    - ansible-install-check-mk-client
    - files

- name: Create directory - spool
  file: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0700
    path: "{{ ansible_install_check_mk_client_home }}/spool"
    state: directory
  tags:
    - ansible-install-check-mk-client
    - files

- name: Create directory - cache
  file: 
    owner: "{{ ansible_install_check_mk_client_user }}" 
    group: "{{ ansible_install_check_mk_client_user }}" 
    mode: 0700
    path: "{{ ansible_install_check_mk_client_home }}/cache"
    state: directory
  tags:
    - ansible-install-check-mk-client
    - files

