---
# tasks file for install-check_mk-client (Windows only)

- name: Copy agent installation file
  win_copy:
    dest: "{{ install_check_mk_client_win_tmp }}"
    src: "{{ install_check_mk_client_win_filename }}"
  register: copy_agent
  tags:
    - install-check-mk-client
    - files

- name: Install agent
  win_msi:
    path: "{{ install_check_mk_client_win_tmp }}"
    state: present
    wait: True
  when: copy_agent.changed
  tags:
    - install-check-mk-client
    - files

- name: Generate configuration file from template
  win_template: 
    src: "{{ install_check_mk_client_win_config }}"
    dest: "{{ install_check_mk_client_win_folder }}check_mk.ini"
  notify: Restart Windows agent service
  tags:
    - install-check-mk-client
    - files

- name: Generate plugins
  win_template: 
    src: "{{ item }}.j2"
    dest: "{{ install_check_mk_client_win_folder }}plugins\\{{ item }}"
  with_items: "{{ install_check_mk_client_win_plugins }}"
  notify: Restart Windows agent service
  tags:
    - install-check-mk-client
    - files

