---
# tasks file for install-cmkagent

# Create required group:
- name: Create monitoring group - cmkagent
  group: 
    name: cmkagent 
    state: present
  tags:
    - install-cmkagent
    - users

# Create required user:
- name: Create monitoring user - cmkagent
  user: 
    name: cmkagent 
    group: cmkagent 
    home: /home/cmkagent
    comment: "Check_MK Agent"
  tags:
    - install-cmkagent
    - users

# Copy Linux agent if Linux:
- name: Copy Linux check_mk_agent to ~cmkagent and set executable
  template: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0755
    src: check_mk_agent.linux.j2
    dest: /home/cmkagent/check_mk_agent
  when: ansible_system.find( 'Linux' ) == 0
  tags:
    - install-cmkagent
    - files

# Grant sudo and verify new file:
- name: Grant sudo for check_mk_agent to monitoring user
  template: 
    owner: root 
    group: root 
    mode: 0440
    src: 99_cmkagent.j2
    dest: /etc/sudoers.d/99_cmkagent
    validate: 'visudo -cf %s'
  tags:
    - install-cmkagent
    - files
    - users

# Make .ssh directory:
- name: Create directory - ~cmkagent/.ssh
  file: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0700
    path: /home/cmkagent/.ssh
    state: directory
  tags:
    - install-cmkagent
    - files
    - users

# Copy SSH key:
- name: Copy public key to ~cmkagent/.ssh/authorized_keys
  template: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0600
    src: authorized_keys.j2
    dest: /home/cmkagent/.ssh/authorized_keys
  tags:
    - install-cmkagent
    - files
    - users

# Make local directory:
- name: Create directory - ~cmkagent/local
  file: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0700
    path: /home/cmkagent/local
    state: directory
  tags:
    - install-cmkagent
    - files

# Copy over any local checks:
- name: Generate local checks
  template: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0700
    src: "{{ item }}.j2"
    dest: "/home/cmkagent/local/{{ item }}"
  with_items: local_checks
  tags:
    - install-cmkagent
    - files

# Make plugins directory:
- name: Create directory - ~cmkagent/plugins
  file: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0700
    path: /home/cmkagent/plugins
    state: directory
  tags:
    - install-cmkagent
    - files

# Copy over any plugins:
- name: Generate plugins
  template: 
    owner: cmkagent
    group: cmkagent
    mode: 0700
    src: "{{ item }}.j2"
    dest: "/home/cmkagent/plugins/{{ item }}"
  with_items: plugins
  tags:
    - install-cmkagent
    - files

# Make spool directory:
- name: Create directory - ~cmkagent/spool
  file: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0700
    path: /home/cmkagent/spool
    state: directory
  tags:
    - install-cmkagent
    - files

# Make cache directory:
- name: Create directory - ~cmkagent/cache
  file: 
    owner: cmkagent 
    group: cmkagent 
    mode: 0700
    path: /home/cmkagent/cache
    state: directory
  tags:
    - install-cmkagent
    - files

# Remove default directory:
- name: Remove /usr/lib/check_mk_agent
  file: 
    path: /usr/lib/check_mk_agent
    state: absent
  tags:
    - install-cmkagent
    - files 

