---
# tasks file for install-cmkagent

# Create required group:
- name: Create monitoring group
  group: 
    name: "{{ install_cmkagent_user }}" 
    state: present
  tags:
    - install-cmkagent
    - users

# Create required user:
- name: Create monitoring user
  user: 
    name: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    home: "{{ install_cmkagent_home }}"
    comment: "Check_MK Agent"
  tags:
    - install-cmkagent
    - users

# Copy Linux agent if Linux:
- name: Copy Linux check_mk_agent and set executable
  template: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0755
    src: check_mk_agent.linux.j2
    dest: "{{ install_cmkagent_home }}/check_mk_agent"
  when: ansible_system.find( 'Linux' ) == 0
  tags:
    - install-cmkagent
    - files

# Grant sudo and verify new file:
- name: Grant sudo for check_mk_agent to monitoring user
  template: 
    owner: root 
    group: root 
    mode: 0440
    src: 99_cmkagent.j2
    dest: /etc/sudoers.d/99_cmkagent
    validate: 'visudo -cf %s'
  tags:
    - install-cmkagent
    - files
    - users

# Make .ssh directory:
- name: Create directory - .ssh
  file: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0700
    path: "{{ install_cmkagent_home }}/.ssh"
    state: directory
  tags:
    - install-cmkagent
    - files
    - users

# Copy SSH key:
- name: Copy public key to .ssh/authorized_keys
  template: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0600
    src: authorized_keys.j2
    dest: "{{ install_cmkagent_home }}/.ssh/authorized_keys"
  tags:
    - install-cmkagent
    - files
    - users

# Make local directory:
- name: Create directory - local
  file: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0700
    path: "{{ install_cmkagent_home }}/local"
    state: directory
  tags:
    - install-cmkagent
    - files

# Copy over any local checks:
- name: Generate local checks
  template: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0700
    src: "{{ item }}.j2"
    dest: "{{ install_cmkagent_home }}/local/{{ item }}"
  with_items: install_cmkagent_local_checks
  tags:
    - install-cmkagent
    - files

# Make plugins directory:
- name: Create directory - plugins
  file: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0700
    path: "{{ install_cmkagent_home }}/plugins"
    state: directory
  tags:
    - install-cmkagent
    - files

# Copy over any plugins:
- name: Generate plugins
  template: 
    owner: "{{ install_cmkagent_user }}"
    group: "{{ install_cmkagent_user }}"
    mode: 0700
    src: "{{ item }}.j2"
    dest: "{{ install_cmkagent_home }}/plugins/{{ item }}"
  with_items: install_cmkagent_plugins
  tags:
    - install-cmkagent
    - files

# Make spool directory:
- name: Create directory - spool
  file: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0700
    path: "{{ install_cmkagent_home }}/spool"
    state: directory
  tags:
    - install-cmkagent
    - files

# Make cache directory:
- name: Create directory - cache
  file: 
    owner: "{{ install_cmkagent_user }}" 
    group: "{{ install_cmkagent_user }}" 
    mode: 0700
    path: "{{ install_cmkagent_home }}/cache"
    state: directory
  tags:
    - install-cmkagent
    - files

# Remove default directory:
- name: Remove /usr/lib/check_mk_agent
  file: 
    path: /usr/lib/check_mk_agent
    state: absent
  tags:
    - install-cmkagent
    - files 

