---
# Override any of these defaults with variables in other roles.
#
# Generate useful password hashes with this command on
#   any system with the "python-passlib" package:
#
# $ python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
#
mkadmins_users:
  tinkermill:
    state: present
    name: TinkerMill Default User
    shell: /bin/bash
    password: $6$rounds=40000$BZ0T/6kGy2tSzepc$.l71BiURGCgZalwQui1Gq37J65yYnwDSs2u7Itzx8XVF5sBkWMDnUMsXOwP9p8ciF71PcuqTpKOgv9HDKPyW2.
  kso:
    state: present
    name: Chris Lindbergh
    shell: /bin/bash
    password: $6$rounds=40000$3FSkLqYlJroTn4kX$uGV8QXb7IphgT2Izckm5CouKzPj1hu4jBcaflWJNjFIsD.MTcGsjiT5AVFpSfLzlGCFWNeHrvrSyjWndB66Ps.
  gofish:
    state: present
    name: Greg Fischer
    shell: /bin/bash
    password: $6$rounds=656000$BlkixggoFPHb0x6b$O5hXcJCjYoL32meqRbZD7DxiXJC8wDSruS.jKyA9vJurnqf.quhGZN3pTp2XAJgkPNB6AMJM8HsvG5MuvxJNZ.
  bwelkerd:
    state: present
    name: Bruce Welker
    shell: /bin/bash
    password: $6$rounds=656000$fbRi7GZJgYcNb.gD$zjFPTdh9/8RGKMDsjuHQLpmv7..G7ZB9O1mlyJztxbVWtTJWwfHBcNWG.f.BbkyRIo2kjEeGBY/pqKtbAZ.vV0
  david:
    state: present
    name: David Leonard
    shell: /bin/bash
    password: $6$rounds=656000$TRik3vdZOs9f2peU$xY530fUYbFkkl23WiupKkayrxQdQN6IhW4wirhzGVXlfGcvSBc8eZ/dZPsuLbcY6NukOHmugUfcZKMVv7IC85.
mkadmins_rc_files:
  - name: kso
    group:
    files:
      - .bashrc
      - .screenrc
      - .vimrc
