---
# tasks file for shell-master
- name: Task | Install required packages
  apt: >
    cache_valid_time=3600
    pkg={{ item }} state=installed
  with_items:
    - ansible
    - git
    - screen
    - sshpass
  tags:
    - shell-master
    - packages
