---
# tasks file for shell-master

# Install required packages:
- name: Install required packages
  apt: 
    cache_valid_time: 3600
    pkg: "{{ shell_master_install_packages_apt }}" 
    state: installed
  tags:
    - shell-master
    - packages

# Replace the SSH client configuration file:
- name: Replace the SSH client configuration file
  template: 
    owner: root
    group: root
    mode: 0644
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
  tags:
    - shell-master
    - files

# Install pip packages:
- name: Install pip packages
  pip:
    name: "{{ shell_master_install_packages_pip }}"
    state: latest
  tags:
    - shell-master
    - packages

