---
# tasks file for shell-master
- name: Install required packages
  apt: 
    cache_valid_time: 3600
    pkg: "{{ item }}" 
    state: installed
  with_items:
    - ansible
    - git
    - screen
    - sshpass
  tags:
    - shell-master
    - packages

- name: Replace the SSH client configuration file
  template: 
    owner: root
    group: root
    mode: 0644
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
  tags:
    - shell-master
    - files
