---
# tasks file for syslog-receiver
- name: Task | Install Rsyslog
  apt: >
    cache_valid_time=3600
    name=rsyslog
    state=present
    update_cache=yes
  tags:
    - syslog-receiver
    - packages

- name: Task | Place the rsyslog configuration file
  template: >
    owner=root
    group=root
    mode=0644
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.conf
  notify: Handler | Restart RsyslogD
  tags:
    - syslog-receiver
    - files
