---
# tasks file for syslog-receiver
- name: Task | Install Rsyslog
  apt: >
    cache_valid_time=3600
    name=rsyslog
    state=present
    update_cache=yes
  tags:
    - syslog-receiver
    - packages

- name: Task | Create the remote log file folder
  file: >
    owner=syslog
    group=adm
    mode=0755
    state=directory
    path={{ syslog_receiver_remote_log_folder }}
  notify: Handler | Restart RsyslogD
  tags:
    - syslog-receiver
    - files

- name: Task | Remove the previous rsyslog configuration file
  template: >
    owner=root
    group=root
    mode=0644
    src=90-syslog-receiver.conf.j2
    dest=/etc/rsyslog.d/90-syslog-receiver.conf
  notify: Handler | Restart RsyslogD
  tags:
    - syslog-receiver
    - files

- name: Task | Place the rsyslog configuration file
  template: >
    owner=root
    group=root
    mode=0644
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.conf
  notify: Handler | Restart RsyslogD
  tags:
    - syslog-receiver
    - files
