---
# tasks file for tinkeraccess-server

# Use git module to clone repository:
- name: Clone repository
  git:
    bare: no
    clone: yes
    dest: "{{ tinkeraccess_repo_dest }}"
    repo: "{{ tinkeraccess_repo_source }}"
  tags:
    - tinkeraccess-server
    - files

# Run the install script:
- name: Run the install script
  shell: "{{ tinkeraccess_repo_dest }}/install.sh"
  args:
    chdir: "{{ tinkeraccess_repo_dest }}"
    creates: /etc/init.d/tinkerserver
  tags:
    - tinkeraccess-server
    - files

# Disable client:
- name: Disable tinkerAccess client
  service:
    enabled: no 
    name: tinkerclient
    state: stopped
  tags:
    - tinkeraccess-server
    - services

# Enable server:
- name: Enable tinkerAccess server
  service:
    enabled: yes
    name: tinkerserver
    state: started
  tags:
    - tinkeraccess-server
    - services

