---
# tasks file for tinkeraccess-server

# Disable DHCP client, avahi-daemon, and bluetooh:
- name: Disable DHCP client, avahi-daemon, and bluetooh
  service:
    enabled: no
    name: "{{ item }}"
    state: stopped
  with_items:
    - dhcpcd
    - avahi-daemon
    - bluetooth
  tags:
    - tinkeraccess-server
    - services

# Disable wifi:
- name: Disable wifi
  lineinfile:
    create: yes
    dest: /etc/modprobe.d/raspi-blacklist.conf
    group: root
    line: "blacklist {{ item }}"
    mode: 0644
    owner: root
    state: present
  with_items:
    - brcmfmac
    - brcmutil
  tags:
    - tinkeraccess-server
    - files

# Set locale to US:
- name: Set locale to en_US
  locale_gen:
    name: en_US.UTF-8
    state: present
  tags:
    - tinkeraccess-server
    - files

# Set timezone; use module once we go to Ansible 2.2:
- name: Set timezone
  shell: timedatectl set-timezone America/Denver
  tags:
    - tinkeraccess-server
    - files

# Use git module to clone repository:
- name: Clone repository
  git:
    bare: no
    clone: yes
    dest: "{{ tinkeraccess_repo_dest }}"
    repo: "{{ tinkeraccess_repo_source }}"
  tags:
    - tinkeraccess-server
    - files

# Run the install script:
- name: Run the install script
  shell: "{{ tinkeraccess_repo_dest }}/install.sh"
  args:
    chdir: "{{ tinkeraccess_repo_dest }}"
    creates: /etc/init.d/tinkerserver
  tags:
    - tinkeraccess-server
    - files

# Disable client:
- name: Disable tinkerAccess client
  service:
    enabled: no 
    name: tinkerclient
    state: stopped
  tags:
    - tinkeraccess-server
    - services

# Enable server:
- name: Enable tinkerAccess server
  service:
    enabled: yes
    name: tinkerserver
    state: started
  tags:
    - tinkeraccess-server
    - services

