---
# handlers file for install-cmkagent

# Restart Windows agent service:
- name: Restart Windows agent service
  win_service:
    name: Check_MK_Agent
    state: restarted
  tags:
    - install-cmkagent
    - files

